// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbJLrko86OStKxeC0pKlO92r_OnCHYT1Y',
    appId: '1:894634281578:web:b0f0cf1c5634e9f374d813',
    messagingSenderId: '894634281578',
    projectId: 'se346-push-notification',
    authDomain: 'se346-push-notification.firebaseapp.com',
    storageBucket: 'se346-push-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt8uf71b835A8v7njwUsGwJ0BcXkiYR5A',
    appId: '1:894634281578:android:0559462727e01ca974d813',
    messagingSenderId: '894634281578',
    projectId: 'se346-push-notification',
    storageBucket: 'se346-push-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOuiNbnOxV9BDyuf7Hn0QVlZW-HT8BgxA',
    appId: '1:894634281578:ios:a83ca56ef57ccd5874d813',
    messagingSenderId: '894634281578',
    projectId: 'se346-push-notification',
    storageBucket: 'se346-push-notification.appspot.com',
    iosClientId: '894634281578-3op2f8ruqrq5e3bbc4gcc79ds6uvrfm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.se346PushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOuiNbnOxV9BDyuf7Hn0QVlZW-HT8BgxA',
    appId: '1:894634281578:ios:a83ca56ef57ccd5874d813',
    messagingSenderId: '894634281578',
    projectId: 'se346-push-notification',
    storageBucket: 'se346-push-notification.appspot.com',
    iosClientId: '894634281578-3op2f8ruqrq5e3bbc4gcc79ds6uvrfm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.se346PushNotification',
  );
}
